// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: can_abort.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.SilaStandard.V2.RealeaseCandidate.CanAbort {

  /// <summary>Holder for reflection information generated from can_abort.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CanAbortReflection {

    #region Descriptor
    /// <summary>File descriptor for can_abort.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CanAbortReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9jYW5fYWJvcnQucHJvdG8SMG9yZy5zaWxhX3N0YW5kYXJkLnYyLnJlYWxl",
            "YXNlX2NhbmRpZGF0ZS5jYW5BYm9ydBoMc3RkbGliLnByb3RvIhwKCmFib3J0",
            "UmVwbHkSDgoGc3RhdHVzGAEgASgJMocBCgVhYm9ydBJ+CgVhYm9ydBI1Lm9y",
            "Zy5zaWxhX3N0YW5kYXJkLnYyLnJlYWxlYXNlX2NhbmRpZGF0ZS5zdGRsaWIu",
            "RW1wdHkaPC5vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFsZWFzZV9jYW5kaWRh",
            "dGUuY2FuQWJvcnQuYWJvcnRSZXBseSIAQjMKGXNpbGEyLmNvbS53ZWdhLWl0",
            "LmNvbW1vbi5CDk1hdHJpeDIwMFByb3RvUAGiAgNNVFhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Org.SilaStandard.V2.RealeaseCandidate.Stdlib.StdlibReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.SilaStandard.V2.RealeaseCandidate.CanAbort.abortReply), global::Org.SilaStandard.V2.RealeaseCandidate.CanAbort.abortReply.Parser, new[]{ "Status" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///  
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class abortReply : pb::IMessage<abortReply> {
    private static readonly pb::MessageParser<abortReply> _parser = new pb::MessageParser<abortReply>(() => new abortReply());
    public static pb::MessageParser<abortReply> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.SilaStandard.V2.RealeaseCandidate.CanAbort.CanAbortReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public abortReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    public abortReply(abortReply other) : this() {
      status_ = other.status_;
    }

    public abortReply Clone() {
      return new abortReply(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private string status_ = "";
    public string Status {
      get { return status_; }
      set {
        status_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as abortReply);
    }

    public bool Equals(abortReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Status.Length != 0) hash ^= Status.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Status.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Status);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Status.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Status);
      }
      return size;
    }

    public void MergeFrom(abortReply other) {
      if (other == null) {
        return;
      }
      if (other.Status.Length != 0) {
        Status = other.Status;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Status = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
