// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: can_read_barcode.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.SilaStandard.V2.RealeaseCandidate.CanReadCode {

  /// <summary>Holder for reflection information generated from can_read_barcode.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CanReadBarcodeReflection {

    #region Descriptor
    /// <summary>File descriptor for can_read_barcode.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CanReadBarcodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZjYW5fcmVhZF9iYXJjb2RlLnByb3RvEjNvcmcuc2lsYV9zdGFuZGFyZC52",
            "Mi5yZWFsZWFzZV9jYW5kaWRhdGUuY2FuUmVhZENvZGUaDHN0ZGxpYi5wcm90",
            "bzLSBAoQY2FuX3JlYWRfYmFyY29kZRKGAQoJcmVhZF9jb2RlEj0ub3JnLnNp",
            "bGFfc3RhbmRhcmQudjIucmVhbGVhc2VfY2FuZGlkYXRlLnN0ZGxpYi5QaHlz",
            "aWNhbFZhbHVlGjYub3JnLnNpbGFfc3RhbmRhcmQudjIucmVhbGVhc2VfY2Fu",
            "ZGlkYXRlLnN0ZGxpYi5TdHJpbmciADABEowBCg9yZWFkX2NvZGVfbm9leHAS",
            "PS5vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFsZWFzZV9jYW5kaWRhdGUuc3Rk",
            "bGliLlBoeXNpY2FsVmFsdWUaNi5vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFs",
            "ZWFzZV9jYW5kaWRhdGUuc3RkbGliLlN0cmluZyIAMAESjAEKB2JhcmNvZGUS",
            "RS5vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFsZWFzZV9jYW5kaWRhdGUuc3Rk",
            "bGliLlNpTEFfUHJvcGVydHlfUmVxdWVzdBo2Lm9yZy5zaWxhX3N0YW5kYXJk",
            "LnYyLnJlYWxlYXNlX2NhbmRpZGF0ZS5zdGRsaWIuU3RyaW5nIgAwARKWAQoQ",
            "aXNfYmFyY29kZV9mb3VuZBJFLm9yZy5zaWxhX3N0YW5kYXJkLnYyLnJlYWxl",
            "YXNlX2NhbmRpZGF0ZS5zdGRsaWIuU2lMQV9Qcm9wZXJ0eV9SZXF1ZXN0Gjcu",
            "b3JnLnNpbGFfc3RhbmRhcmQudjIucmVhbGVhc2VfY2FuZGlkYXRlLnN0ZGxp",
            "Yi5Cb29sZWFuIgAwAUJACiZzaWxhMi5jb20ud2VnYS1pdC5jb21tb24uYmFy",
            "Y29kZVJlYWRlckIOTWF0cml4MjAwUHJvdG9QAaICA01UWGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Org.SilaStandard.V2.RealeaseCandidate.Stdlib.StdlibReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
