// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: can_set_configuration.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration {

  /// <summary>Holder for reflection information generated from can_set_configuration.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CanSetConfigurationReflection {

    #region Descriptor
    /// <summary>File descriptor for can_set_configuration.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CanSetConfigurationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtjYW5fc2V0X2NvbmZpZ3VyYXRpb24ucHJvdG8SO29yZy5zaWxhX3N0YW5k",
            "YXJkLnYyLnJlYWxlYXNlX2NhbmRpZGF0ZS5jYW5TZXRDb25maWd1cmF0aW9u",
            "GgxzdGRsaWIucHJvdG8iFwoGc3RhdHVzEg0KBXZhbHVlGAEgASgJIgcKBUVt",
            "cHR5IjUKFkNvbmZpZ3VyYXRpb25QYXJhbWV0ZXISDAoEbmFtZRgBIAEoCRIN",
            "CgV2YWx1ZRgCIAEoCSJuChpCYXJjb2RlUmVhZGVyQ29uZmlndXJhdGlvbhIQ",
            "CghiYXVkUmF0ZRgBIAEoCRIVCg1jb25uZXRpb25UeXBlGAIgASgJEhUKDWRl",
            "dmljZUFkZHJlc3MYAyABKAkSEAoIcG9ydE5hbWUYBCABKAkyiAMKHWNhbkJh",
            "cmNvZGVSZWFkZXJDb25maWd1cmF0aW9uErIBChBzZXRDb25maWd1cmF0aW9u",
            "Elcub3JnLnNpbGFfc3RhbmRhcmQudjIucmVhbGVhc2VfY2FuZGlkYXRlLmNh",
            "blNldENvbmZpZ3VyYXRpb24uQmFyY29kZVJlYWRlckNvbmZpZ3VyYXRpb24a",
            "Qy5vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFsZWFzZV9jYW5kaWRhdGUuY2Fu",
            "U2V0Q29uZmlndXJhdGlvbi5zdGF0dXMiABKxAQoQZ2V0Q29uZmlndXJhdGlv",
            "bhJCLm9yZy5zaWxhX3N0YW5kYXJkLnYyLnJlYWxlYXNlX2NhbmRpZGF0ZS5j",
            "YW5TZXRDb25maWd1cmF0aW9uLkVtcHR5Glcub3JnLnNpbGFfc3RhbmRhcmQu",
            "djIucmVhbGVhc2VfY2FuZGlkYXRlLmNhblNldENvbmZpZ3VyYXRpb24uQmFy",
            "Y29kZVJlYWRlckNvbmZpZ3VyYXRpb24iADLIAQoTY2FuU2V0Q29uZmlndXJh",
            "dGlvbhKwAQoSc2V0Q29uZmlnUGFyYW1ldGVyElMub3JnLnNpbGFfc3RhbmRh",
            "cmQudjIucmVhbGVhc2VfY2FuZGlkYXRlLmNhblNldENvbmZpZ3VyYXRpb24u",
            "Q29uZmlndXJhdGlvblBhcmFtZXRlchpDLm9yZy5zaWxhX3N0YW5kYXJkLnYy",
            "LnJlYWxlYXNlX2NhbmRpZGF0ZS5jYW5TZXRDb25maWd1cmF0aW9uLnN0YXR1",
            "cyIAMtgBChRjYW5SZWFkQ29uZmlndXJhdGlvbhK/AQoRZ2V0Q29uZmlnUGFy",
            "YW10ZXISUy5vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFsZWFzZV9jYW5kaWRh",
            "dGUuY2FuU2V0Q29uZmlndXJhdGlvbi5Db25maWd1cmF0aW9uUGFyYW1ldGVy",
            "GlMub3JnLnNpbGFfc3RhbmRhcmQudjIucmVhbGVhc2VfY2FuZGlkYXRlLmNh",
            "blNldENvbmZpZ3VyYXRpb24uQ29uZmlndXJhdGlvblBhcmFtZXRlciIAQlAK",
            "NnNpbGEyLmNvbS53ZWdhLWl0LmNvbW1vbi5jYW5CYXJjb2RlUmVhZGVyQ29u",
            "ZmlndXJhdGlvbkIOTWF0cml4MjAwUHJvdG9QAaICA01UWGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Org.SilaStandard.V2.RealeaseCandidate.Stdlib.StdlibReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.status), global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.status.Parser, new[]{ "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.Empty), global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.Empty.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.ConfigurationParameter), global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.ConfigurationParameter.Parser, new[]{ "Name", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.BarcodeReaderConfiguration), global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.BarcodeReaderConfiguration.Parser, new[]{ "BaudRate", "ConnetionType", "DeviceAddress", "PortName" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class status : pb::IMessage<status> {
    private static readonly pb::MessageParser<status> _parser = new pb::MessageParser<status>(() => new status());
    public static pb::MessageParser<status> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.CanSetConfigurationReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public status() {
      OnConstruction();
    }

    partial void OnConstruction();

    public status(status other) : this() {
      value_ = other.value_;
    }

    public status Clone() {
      return new status(this);
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 1;
    private string value_ = "";
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as status);
    }

    public bool Equals(status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Value != other.Value) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Value.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Value);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      return size;
    }

    public void MergeFrom(status other) {
      if (other == null) {
        return;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Value = input.ReadString();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Empty : pb::IMessage<Empty> {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.CanSetConfigurationReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Empty(Empty other) : this() {
    }

    public Empty Clone() {
      return new Empty(this);
    }

    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
    }

    public int CalculateSize() {
      int size = 0;
      return size;
    }

    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ConfigurationParameter : pb::IMessage<ConfigurationParameter> {
    private static readonly pb::MessageParser<ConfigurationParameter> _parser = new pb::MessageParser<ConfigurationParameter>(() => new ConfigurationParameter());
    public static pb::MessageParser<ConfigurationParameter> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.CanSetConfigurationReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public ConfigurationParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    public ConfigurationParameter(ConfigurationParameter other) : this() {
      name_ = other.name_;
      value_ = other.value_;
    }

    public ConfigurationParameter Clone() {
      return new ConfigurationParameter(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private string value_ = "";
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as ConfigurationParameter);
    }

    public bool Equals(ConfigurationParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Value != other.Value) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Value);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      return size;
    }

    public void MergeFrom(ConfigurationParameter other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Value = input.ReadString();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class BarcodeReaderConfiguration : pb::IMessage<BarcodeReaderConfiguration> {
    private static readonly pb::MessageParser<BarcodeReaderConfiguration> _parser = new pb::MessageParser<BarcodeReaderConfiguration>(() => new BarcodeReaderConfiguration());
    public static pb::MessageParser<BarcodeReaderConfiguration> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.SilaStandard.V2.RealeaseCandidate.CanSetConfiguration.CanSetConfigurationReflection.Descriptor.MessageTypes[3]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public BarcodeReaderConfiguration() {
      OnConstruction();
    }

    partial void OnConstruction();

    public BarcodeReaderConfiguration(BarcodeReaderConfiguration other) : this() {
      baudRate_ = other.baudRate_;
      connetionType_ = other.connetionType_;
      deviceAddress_ = other.deviceAddress_;
      portName_ = other.portName_;
    }

    public BarcodeReaderConfiguration Clone() {
      return new BarcodeReaderConfiguration(this);
    }

    /// <summary>Field number for the "baudRate" field.</summary>
    public const int BaudRateFieldNumber = 1;
    private string baudRate_ = "";
    public string BaudRate {
      get { return baudRate_; }
      set {
        baudRate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "connetionType" field.</summary>
    public const int ConnetionTypeFieldNumber = 2;
    private string connetionType_ = "";
    public string ConnetionType {
      get { return connetionType_; }
      set {
        connetionType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deviceAddress" field.</summary>
    public const int DeviceAddressFieldNumber = 3;
    private string deviceAddress_ = "";
    public string DeviceAddress {
      get { return deviceAddress_; }
      set {
        deviceAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "portName" field.</summary>
    public const int PortNameFieldNumber = 4;
    private string portName_ = "";
    public string PortName {
      get { return portName_; }
      set {
        portName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as BarcodeReaderConfiguration);
    }

    public bool Equals(BarcodeReaderConfiguration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BaudRate != other.BaudRate) return false;
      if (ConnetionType != other.ConnetionType) return false;
      if (DeviceAddress != other.DeviceAddress) return false;
      if (PortName != other.PortName) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (BaudRate.Length != 0) hash ^= BaudRate.GetHashCode();
      if (ConnetionType.Length != 0) hash ^= ConnetionType.GetHashCode();
      if (DeviceAddress.Length != 0) hash ^= DeviceAddress.GetHashCode();
      if (PortName.Length != 0) hash ^= PortName.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (BaudRate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BaudRate);
      }
      if (ConnetionType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ConnetionType);
      }
      if (DeviceAddress.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DeviceAddress);
      }
      if (PortName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(PortName);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (BaudRate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BaudRate);
      }
      if (ConnetionType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConnetionType);
      }
      if (DeviceAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceAddress);
      }
      if (PortName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PortName);
      }
      return size;
    }

    public void MergeFrom(BarcodeReaderConfiguration other) {
      if (other == null) {
        return;
      }
      if (other.BaudRate.Length != 0) {
        BaudRate = other.BaudRate;
      }
      if (other.ConnetionType.Length != 0) {
        ConnetionType = other.ConnetionType;
      }
      if (other.DeviceAddress.Length != 0) {
        DeviceAddress = other.DeviceAddress;
      }
      if (other.PortName.Length != 0) {
        PortName = other.PortName;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            BaudRate = input.ReadString();
            break;
          }
          case 18: {
            ConnetionType = input.ReadString();
            break;
          }
          case 26: {
            DeviceAddress = input.ReadString();
            break;
          }
          case 34: {
            PortName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
