// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: is_Sila.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.SilaStandard.V2.RealeaseCandidate.IsSila {

  /// <summary>Holder for reflection information generated from is_Sila.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class IsSilaReflection {

    #region Descriptor
    /// <summary>File descriptor for is_Sila.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IsSilaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1pc19TaWxhLnByb3RvEi9vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFsZWFz",
            "ZV9jYW5kaWRhdGUuaXNfc2lsYRoMc3RkbGliLnByb3RvMq8GCgdpc19zaWxh",
            "EncKBHdzZGwSNS5vcmcuc2lsYV9zdGFuZGFyZC52Mi5yZWFsZWFzZV9jYW5k",
            "aWRhdGUuc3RkbGliLkVtcHR5GjYub3JnLnNpbGFfc3RhbmRhcmQudjIucmVh",
            "bGVhc2VfY2FuZGlkYXRlLnN0ZGxpYi5TdHJpbmciABKJAQoWc2lsYV9pbnRl",
            "cmZhY2VfdmVyc2lvbhI1Lm9yZy5zaWxhX3N0YW5kYXJkLnYyLnJlYWxlYXNl",
            "X2NhbmRpZGF0ZS5zdGRsaWIuRW1wdHkaNi5vcmcuc2lsYV9zdGFuZGFyZC52",
            "Mi5yZWFsZWFzZV9jYW5kaWRhdGUuc3RkbGliLlN0cmluZyIAEoYBChNkZXZp",
            "Y2VfbWFudWZhY3R1cmVyEjUub3JnLnNpbGFfc3RhbmRhcmQudjIucmVhbGVh",
            "c2VfY2FuZGlkYXRlLnN0ZGxpYi5FbXB0eRo2Lm9yZy5zaWxhX3N0YW5kYXJk",
            "LnYyLnJlYWxlYXNlX2NhbmRpZGF0ZS5zdGRsaWIuU3RyaW5nIgASfwoMc2Vy",
            "dmljZV9uYW1lEjUub3JnLnNpbGFfc3RhbmRhcmQudjIucmVhbGVhc2VfY2Fu",
            "ZGlkYXRlLnN0ZGxpYi5FbXB0eRo2Lm9yZy5zaWxhX3N0YW5kYXJkLnYyLnJl",
            "YWxlYXNlX2NhbmRpZGF0ZS5zdGRsaWIuU3RyaW5nIgAShwEKFGRldmljZV9z",
            "ZXJpYWxfbnVtYmVyEjUub3JnLnNpbGFfc3RhbmRhcmQudjIucmVhbGVhc2Vf",
            "Y2FuZGlkYXRlLnN0ZGxpYi5FbXB0eRo2Lm9yZy5zaWxhX3N0YW5kYXJkLnYy",
            "LnJlYWxlYXNlX2NhbmRpZGF0ZS5zdGRsaWIuU3RyaW5nIgASigEKF2Rldmlj",
            "ZV9maXJtd2FyZV92ZXJzaW9uEjUub3JnLnNpbGFfc3RhbmRhcmQudjIucmVh",
            "bGVhc2VfY2FuZGlkYXRlLnN0ZGxpYi5FbXB0eRo2Lm9yZy5zaWxhX3N0YW5k",
            "YXJkLnYyLnJlYWxlYXNlX2NhbmRpZGF0ZS5zdGRsaWIuU3RyaW5nIgBiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Org.SilaStandard.V2.RealeaseCandidate.Stdlib.StdlibReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
